version: '3.0'
services:
  streetmerchant:
    image: docker.io/thatguykalvin/streetmerchant:latest   
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streetmerchant
    env_file:
      - dotenv
